# Generated by Django 5.1.4 on 2025-01-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DieselCars',
            fields=[
                ('brand', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='allcars')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricCars',
            fields=[
                ('brand', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='allcars')),
            ],
        ),
        migrations.CreateModel(
            name='PetrolCars',
            fields=[
                ('brand', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='allcars')),
            ],
        ),
    ]
