# Generated by Django 5.1.4 on 2025-01-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0002_dieselcars_electriccars_petrolcars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bikes')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
