# Generated by Django 5.1.4 on 2025-01-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0002_car_fuel_type_alter_car_category'),
        ('mini', '0003_bike'),
        ('mini', '0004_profile'),
    ]

    operations = [
    ]
