# Generated by Django 5.1.4 on 2025-01-10 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0006_favorite_favoriteitem_delete_bike_delete_dieselcars_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_additional_images')),
                ('description', models.TextField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='mini.car')),
            ],
        ),
    ]
