# Generated by Django 5.1.3 on 2025-01-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0007_caradditionalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
