# Generated by Django 5.1.3 on 2025-01-12 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0008_alter_car_fuel_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarAdditionalImage',
        ),
    ]
