# Generated by Django 5.1.4 on 2025-01-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0009_delete_caradditionalimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profilepicture'),
        ),
    ]
