# Generated by Django 5.1.4 on 2025-01-19 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0010_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(blank=True, max_length=100, null=True)),
                ('transmission', models.CharField(blank=True, max_length=100, null=True)),
                ('mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='mini.car')),
            ],
        ),
    ]
