# Generated by Django 5.1.4 on 2025-01-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0011_cardetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetail',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='car_details'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='car_details'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='car_details'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='car_details'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='car_details'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='car_details'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='car_details'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='car_details'),
        ),
    ]
