# Generated by Django 5.1.4 on 2025-01-22 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0012_cardetail_image1_cardetail_image2_cardetail_image3_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('img1', models.ImageField(blank=True, null=True, upload_to='post_images')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='post_images')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='post_images')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='post_images')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='post_images')),
                ('img6', models.ImageField(blank=True, null=True, upload_to='post_images')),
                ('img7', models.ImageField(blank=True, null=True, upload_to='post_images')),
                ('img8', models.ImageField(blank=True, null=True, upload_to='post_images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
