# Generated by Django 5.1.4 on 2025-01-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0013_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='img6',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='img7',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='img8',
        ),
    ]
