# Generated by Django 5.1.4 on 2025-01-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0014_remove_posts_img2_remove_posts_img3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
